# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip.xci
# IP: The module: 'iiram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iiram_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip.xci
# IP: The module: 'iiram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iiram_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
