# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir S:/Vivado/cpu_31/cpu_31.cache/wt [current_project]
set_property parent.project_path S:/Vivado/cpu_31/cpu_31.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip.xci
set_property is_locked true [get_files S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top iiram_ip -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all iiram_ip_

write_checkpoint -force -noxdef iiram_ip.dcp

catch { report_utilization -file iiram_ip_utilization_synth.rpt -pb iiram_ip_utilization_synth.pb }

if { [catch {
  file copy -force S:/Vivado/cpu_31/cpu_31.runs/iiram_ip_synth_1/iiram_ip.dcp S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir S:/Vivado/cpu_31/cpu_31.ip_user_files/ip/iiram_ip]} {
  catch { 
    file copy -force S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_stub.v S:/Vivado/cpu_31/cpu_31.ip_user_files/ip/iiram_ip
  }
}

if {[file isdir S:/Vivado/cpu_31/cpu_31.ip_user_files/ip/iiram_ip]} {
  catch { 
    file copy -force S:/Vivado/cpu_31/cpu_31.srcs/sources_1/ip/iiram_ip/iiram_ip_stub.vhdl S:/Vivado/cpu_31/cpu_31.ip_user_files/ip/iiram_ip
  }
}
